commands = [
  "export DEBIAN_FRONTEND=noninteractive",
  "sudo apt update",
  "sudo add-apt-repository \"deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu$(lsb_release -rs)/x86_64/ /\"",
  "sudo apt update",
  "sudo apt-get -y install nvidia-cuda-toolkit",
  "sudo apt install nvidia-cuda-toolkit",
  "nvcc vector-add.cu -o vector_add",
  "./vector_add"
]
optimization_priority = "TIME"
gpu = "T4"
